Add `TextGenerationWithImage` task
argilla-io/distilabel pull request #1066
Opened 2024-11-20 16:00 UTC by plaguss

## Description

This PR adds a `VisionGeneration` task to work with image-tex-to-text tasks (chatting with images).

```python
with Pipeline(name="vision_generation_pipeline") as pipeline:
    loader = LoadDataFromDicts(
        data=[
            {
                "instruction": "What’s in this image?",
                "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Gfp-wisconsin-madison-the-nature-boardwalk.jpg/2560px-Gfp-wisconsin-madison-the-nature-boardwalk.jpg"
            }
        ],
    )

    vision = TextGenerationWithImage(
        name="vision_gen",
        llm=InferenceEndpointsLLM(
            model_id="meta-llama/Llama-3.2-11B-Vision-Instruct",
        ),
        image_type="url"
    )

    loader >> vision
```

It has been tested with `InferenceEndpointsLLM` and `OpenAILLM`. There are differences across providers, so we need more tests to ensure the remaining are working, specifically, `vLLM` internally calls to `llm.chat` instead of `llm.generate`, so we need to update it for the vision case

2024-11-27 14:33 UTC, burtenshaw commented
@plaguss Just an API level observation, but does it make sense for `VisionGeneration` to be task? because it means that it cannot be combined with other tasks. Like for example, you could not do `SelfInstruct` on an image of a document.

Also `VisionGeneration` needs logic and behaviour that is generally in the `llms` module, like processing messages.

2024-12-02 12:54 UTC, burtenshaw commented
Here are some use cases that would require vision language models.
- caption generation
- video caption generation
- DocVQA on pdf (SelfInstruct)
- Judge (ultrafeedback ++) on image generation

2024-12-05 12:39 UTC, gabrielmbmb requested changes
Looks good! Just a few changes needed.

I've discussed with @plaguss, at least for now, to keep the specific task to handle the text generation with an VLM until we found a better interface that allows to use any VLM with any task (such as SelfInstruct).

2024-12-05 12:39 UTC, gabrielmbmb commented on src/distilabel/steps/tasks/typing.py
>      content: str
Let's update the type of `content` to something like `Union[str, TextContent, ImageContent]` instead of creating more types like `ConversationType`

2024-12-05 12:39 UTC, gabrielmbmb commented on src/distilabel/steps/tasks/vision_generation.py
> +        return f"data:image/jpeg;base64,{image_to_str(image)}"
```suggestion
        if self.image_type == "url":
            return image
            
        if self.image_type == "base64":
            return f"data:image/jpeg;base64,{image}"
            
        # Othwerwise, it's a PIL image
        return f"data:image/jpeg;base64,{image_to_str(image)}"
```

2024-12-05 12:39 UTC, gabrielmbmb commented on src/distilabel/steps/tasks/vision_generation.py
> +    return base64.b64encode(buffered.getvalue()).decode("utf-8")
maybe we can move this to a module `utils/image.py`?

2024-12-05 12:39 UTC, gabrielmbmb commented on src/distilabel/steps/tasks/vision_generation.py
> +        - vision-generation
I think we can just simply use `text-generation`

2024-12-09 10:27 UTC, merged