feat: Add `EvolComplexity` and `EvolQuality`
argilla-io/distilabel pull request #299
Opened 2024-01-24 17:40 UTC by davidberenstein1957

2024-01-25 16:59 UTC, davidberenstein1957 commented
docs are still WIP @plaguss

2024-01-25 17:23 UTC, plaguss reviewed
Nice! Just a reminder in the docstrings for one of the references. The only thing I'm not sure is if it makes sense to keep both `EvolInstruct` and `EvolComplexity`, to avoid complexity for the users.

2024-01-25 17:23 UTC, plaguss commented on src/distilabel/tasks/text_generation/evol_quality.py
> +        - [`WizardLM: Empowering Large Language Models to Follow Complex Instructions`](https://arxiv.org/abs/2304.12244)
Update the reference to the Deita Paper

2024-01-30 14:59 UTC, gabrielmbmb requested changes
Hi! Looks good to me, I left some comments before merging

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_complexity.py
> +logger = get_logger()
we can remove the `logger` if it's not being used

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_quality.py
> +            The eliminatin step is applied to the output, but only steps 2-4 in the paper are implemented.
```suggestion
            The elimination step is applied to the output, but only steps 2-4 in the paper are implemented.
```

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_quality.py
> +    pass
remove this

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_quality.py
> +logger = get_logger()
not used

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_complexity.py
> +class EvolComplexityGeneratorTask(EvolInstructTask):
I would change the name of this class to just simply `EvolComplexityTask` or if we want to keep the reference of `generation` then I would align the name with the `TextGenerationTask` and call it `EvolComplexityGenerationTask`.

2024-01-30 14:59 UTC, gabrielmbmb commented on src/distilabel/tasks/text_generation/evol_quality.py
> +class EvolQualityGeneratorTask(EvolInstructTask):
Same, I would call it `EvolQualityTask`

2024-01-30 15:03 UTC, gabrielmbmb commented
Also, could we add a unit test covering the Evol Quality Task use of the method `_elimination_evolving` with `response_words`?

2024-01-31 10:13 UTC, davidberenstein1957 commented on tests/tasks/text_generation/test_evol_tasks.py
> +        print("---COSA")
what is happening here?

2024-01-31 10:14 UTC, plaguss commented on tests/tasks/text_generation/test_evol_tasks.py
> +        print("---COSA")
ups, forgot to remove those

2024-01-31 10:25 UTC, plaguss commented
> Also, could we add a unit test covering the Evol Quality Task use of the method `_elimination_evolving` with `response_words`?

Here it is: https://github.com/argilla-io/distilabel/pull/299/commits/7c309aa01dd79597adb597c52ee076c5ef19aa50. If the tests pass, and the docs are correct, I'll merge it

2024-01-31 10:57 UTC, merged