Add requirements list for a pipeline
argilla-io/distilabel pull request #720
Opened 2024-06-11 13:15 UTC by plaguss

## Description

⚠️ WIP

This PR adds a new attribute to `requirements` to `BasePipeline` to keep track of the dependencies needed to run a `Pipeline`.

- [x] `BasePipeline.requirements_to_install()` 
- [ ] Decorator to include requirements on a (custom) step to be passed to the pipeline.
- [ ] Dump the requirements of a Pipeline to `pipeline.yaml`
- [ ] Retrieve the dependencies to check which ones aren't available.
    - [ ] Throw an error and don't run the pipeline in that case.

2024-06-26 11:07 UTC, gabrielmbmb requested changes
Looks good!

2024-06-26 11:07 UTC, gabrielmbmb commented on src/distilabel/utils/requirements.py
> +def add_requirements(requirements: Union[List[str]]) -> "Step":
I would call this `requirements` instead of `add_requirements`, I think is more declarative.

2024-06-26 11:07 UTC, gabrielmbmb commented on src/distilabel/utils/requirements.py
> +def add_requirements(requirements: Union[List[str]]) -> "Step":
Also, the return type hint is wrong, it should be `Callable[["Step"], "Step"]`. Also, we should create a `TypeVar` bound to `_Step`. With the current setup the type of any class decorated will be coerced to `Step` (won't keep their original type)

2024-06-26 15:11 UTC, plaguss commented on src/distilabel/mixins/requirements.py
> +        return self._requirements
In the way we intend to use it, this cannot happen, so I would go with the second option

2024-06-27 09:54 UTC, gabrielmbmb approved these changes
LGTM!

2024-06-27 09:54 UTC, gabrielmbmb commented on docs/sections/how_to_guides/advanced/pipeline_requirements.md
> +to warn the user if something isn't installed and avoid errors when running.
```suggestion
When sharing a `Pipeline` that contains custom `Step`s or `Task`s, you may want to add the specific requirements that are needed to run them. `distilabel` will take this list of requirements and warn the user if any are missing.
```

2024-06-27 09:54 UTC, gabrielmbmb commented on docs/sections/how_to_guides/advanced/pipeline_requirements.md
> +You can now add requirements at the step level as well as on the pipeline. The following is a sample pipeline that adds requirements `nltk` as a dependency to a sample `CustomStep`, and we also infor
```suggestion
Let's see how we can add additional requirements with an example. The first thing we're going to do is to add requirements for our `CustomStep`. To do so we use the `requirements` decorator to specify that the step has `nltk>=3.8` as dependency (we can use [version specifiers](https://peps.python.org/pep-0440/#version-specifiers)). In addition, we're going to specify at `Pipeline` level that we need `distilabel>=1.3.0` to run it.
```

2024-06-27 09:54 UTC, gabrielmbmb commented on docs/sections/how_to_guides/advanced/pipeline_requirements.md
> +pipeline.run()
```suggestion

if __name__ == "__main__":
    pipeline.run()
```

2024-06-27 09:54 UTC, gabrielmbmb commented on docs/sections/how_to_guides/advanced/pipeline_requirements.md
> +Once we call `pipeline.run()`, if any of the requirements informed at the `Step` or `Pipeline` level isn't met, a `ValueError` will be raised telling us that we should install the list of dependencie
```suggestion
Once we call `pipeline.run()`, if any of the requirements informed at the `Step` or `Pipeline` level is missing, a `ValueError` will be raised telling us that we should install the list of dependencies:
```

2024-06-27 09:54 UTC, gabrielmbmb commented on mkdocs.yml
> +          - Impose requirements to your pipelines and steps: "sections/how_to_guides/advanced/pipeline_requirements.md"
```suggestion
          - Specify requirements for pipelines and steps: "sections/how_to_guides/advanced/pipeline_requirements.md"
```

2024-06-27 09:54 UTC, gabrielmbmb commented on src/distilabel/pipeline/base.py
> +            raise ValueError(msg)
maybe here is better a `ModuleNotFoundError`?

2024-06-27 10:06 UTC, merged