Feat/810 feature add huggingface hubutilstelemetry
argilla-io/distilabel pull request #916
Opened 2024-08-20 10:37 UTC by davidberenstein1957

Closes #810

2024-08-20 13:32 UTC, plaguss requested changes
Instead of adding the calls to `add_step` and `add_edge`, we could send the information of `pipeline.dump()` on `BasePipeline.run` so we have all the relevant information we already use for serialization/caching? It would be a single call containing all the information from the pipeline.

I think it could be useful tracking the exceptions raised from the pipeline as you mention, maybe in the `_StepWrapper` would be easier, as that's the container in charge of running the steps on each process.

2024-08-20 13:32 UTC, plaguss commented on tests/integration/test_telemetry.py
> +]
```suggestion
DATA = [
    {"prompt": "Tell me a joke"},
    {"prompt": "Write a short haiku"},
    {"prompt": "Translate 'My name is Alvaro' to Spanish"},
    {"prompt": "What's the capital of Spain?"}
] * 10
```

2024-08-20 13:32 UTC, plaguss commented on tests/integration/test_telemetry.py
> +        rename_columns.connect(generate_response)
```suggestion
        load_dataset >> rename_columns >> generate_response
```

2024-08-20 17:58 UTC, plaguss commented
Not sure how are we going to access the data afterwards to generate the data, I guess it depends, but accessing the dump of the pipeline and cleaning the content we don't want from there I think it's easier, at least from the point of view of `distilabel`, not sure if this is the best way of accessing tracking the telemetry data.

For the exceptions I'm really not sure of what should we track, I guess everything that it's a user error, so you are right not tracking at the `_StepWrapper` level.

2024-08-22 07:19 UTC, davidberenstein1957 commented
@plaguss, I will do the pipeline thingies based on the dump and make individual calls from the telemetry clients instead.

@gabrielmbmb any specific exceptions you would like to see captured? I capture the RuntimeErrors but perhaps some users errors would be interesting, not sure what we can capture cleanly without filling the code up with try-excepts. 

Also, we can start with this and consider adding more at a later stage, in case we feel miss anything.

2024-08-22 09:58 UTC, davidberenstein1957 commented
> @plaguss, I will do the pipeline thingies based on the dump and make individual calls from the telemetry clients instead.
> 
> @gabrielmbmb any specific exceptions you would like to see captured? I capture the RuntimeErrors but perhaps some users errors would be interesting, not sure what we can capture cleanly without filling the code up with try-excepts.
> 
> Also, we can start with this and consider adding more at a later stage, in case we feel miss anything.

@plaguss, I updated the code. Decided to leave the batching and we lost some tracking differentiation for generator, normal and global steps.

2024-09-18 10:34 UTC, closed without merging